const PERFUMES_DB = [
  // ================= MASCULINOS =================
  {
    id: 1,
    name: "Sauvage Eau de Parfum",
    brand: "Dior",
    gender: "Masculino",
    salesRank: 1,
    rating: 4.8,
    family: "Cítrico/Fresco",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Dia a Dia / Trabalho", "Encontro / Romance"],
    topNotes: "Bergamota da Calábria, Pimenta",
    heartNotes: "Pimenta de Sichuan, Lavanda, Noz-moscada",
    baseNotes: "Ambroxan, Baunilha de Papua-Nova Guiné",
    description: "O campeão de vendas indiscutível. Uma composição fresca, potente e envolvente sustentada pela assinatura marcante do ambroxan e baunilha.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 2,
    name: "Bleu de Chanel Parfum",
    brand: "Chanel",
    gender: "Masculino",
    salesRank: 2,
    rating: 4.9,
    family: "Amadeirado",
    intensity: "Intensa",
    occasions: ["Formal / Gala", "Dia a Dia / Trabalho", "Encontro / Romance"],
    topNotes: "Casca de Limão, Bergamota, Hortelã",
    heartNotes: "Lavanda, Gerânio, Abacaxi",
    baseNotes: "Sândalo da Nova Caledônia, Cedro, Fava Tonka",
    description: "O ápice da elegância masculina moderna. Profundo, nobre, denso e versátil com um sândalo cremoso inconfundível.",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 3,
    name: "Aventus",
    brand: "Creed",
    gender: "Masculino",
    salesRank: 3,
    rating: 4.7,
    family: "Frutado / Amadeirado",
    intensity: "Intensa",
    occasions: ["Formal / Gala", "Dia a Dia / Trabalho", "Verão / Calor"],
    topNotes: "Abacaxi, Bergamota, Groselha Preta, Maçã",
    heartNotes: "Bétula, Patchouli, Jasmim Marroquino, Rosa",
    baseNotes: "Almíscar, Musgo de Carvalho, Âmbar Cinzento, Baunilha",
    description: "Fragrância lendária de nicho inspirada em conquistadores históricos. O contraste icônico entre abacaxi suculento e fumaça de bétula.",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 4,
    name: "Acqua di Giò Profondo",
    brand: "Giorgio Armani",
    gender: "Masculino",
    salesRank: 4,
    rating: 4.7,
    family: "Aquático/Aromático",
    intensity: "Intensa",
    occasions: ["Verão / Calor", "Dia a Dia / Trabalho"],
    topNotes: "Notas Marinhas, Aquozone, Bergamota Verde",
    heartNotes: "Alecrim, Cipreste, Lavanda",
    baseNotes: "Notas Minerais, Almíscar, Patchouli, Âmbar",
    description: "Um mergulho contemporâneo no oceano profundo. Frescor aquático refinado com fundo amadeirado aromático e mineral.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 5,
    name: "Le Male Le Parfum",
    brand: "Jean Paul Gaultier",
    gender: "Masculino",
    salesRank: 5,
    rating: 4.9,
    family: "Oriental/Âmbar",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Clima Frio", "Encontro / Romance"],
    topNotes: "Cardamomo",
    heartNotes: "Lavanda, Íris",
    baseNotes: "Baunilha, Notas Orientais, Madeiras Nobres",
    description: "O capitão mais sedutor dos mares. Uma explosão elegante de cardamomo temperada com íris sofisticada e baunilha escura.",
    image: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 6,
    name: "Y Eau de Parfum",
    brand: "Yves Saint Laurent",
    gender: "Masculino",
    salesRank: 6,
    rating: 4.6,
    family: "Aquático/Aromático",
    intensity: "Intensa",
    occasions: ["Dia a Dia / Trabalho", "Noite / Balada", "Verão / Calor"],
    topNotes: "Maçã, Gengibre, Bergamota",
    heartNotes: "Sálvia, Bagas de Zimbro, Gerânio",
    baseNotes: "Fava Tonka, Cedro, Olíbano, Vetiver",
    description: "O azul doce e moderno definitivo. Abertura crocante de maçã com corpo aromático de sálvia e fixação excelente.",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 7,
    name: "Spicebomb Extreme",
    brand: "Viktor&Rolf",
    gender: "Masculino",
    salesRank: 7,
    rating: 4.8,
    family: "Oriental/Âmbar",
    intensity: "Bomba",
    occasions: ["Clima Frio", "Noite / Balada"],
    topNotes: "Pimenta Preta, Canela",
    heartNotes: "Tabaco, Cominho",
    baseNotes: "Baunilha Bourbon, Âmbar",
    description: "Uma granada incendiária de especiarias quentes e tabaco adocicado por uma baunilha licorosa para dias gelados.",
    image: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 8,
    name: "Noir Extreme Parfum",
    brand: "Tom Ford",
    gender: "Masculino",
    salesRank: 8,
    rating: 4.8,
    family: "Gourmand",
    intensity: "Intensa",
    occasions: ["Encontro / Romance", "Formal / Gala", "Clima Frio"],
    topNotes: "Cardamomo, Gengibre, Mandarina, Néroli",
    heartNotes: "Kulfi Indiano, Rosa, Jasmim, Flor de Laranjeira",
    baseNotes: "Baunilha de Madagascar, Camurça, Âmbar, Fava Tonka",
    description: "Sedução pura baseada na sobremesa imperial indiana Kulfi. Cremoso, especiado, refinado e com rastro magnético.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 9,
    name: "Stronger With You Intensely",
    brand: "Giorgio Armani",
    gender: "Masculino",
    salesRank: 9,
    rating: 4.7,
    family: "Gourmand",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Clima Frio", "Encontro / Romance"],
    topNotes: "Pimenta Rosa, Zimbro, Violeta",
    heartNotes: "Caramelo Toffee, Canela, Lavanda, Sálvia",
    baseNotes: "Baunilha, Fava Tonka, Âmbar, Camurça",
    description: "Extremamente viciante. Uma combinação quente de caramelo toffee, canela e baunilha com projeção impressionante.",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 10,
    name: "Layton",
    brand: "Parfums de Marly",
    gender: "Masculino",
    salesRank: 10,
    rating: 4.8,
    family: "Oriental/Âmbar",
    intensity: "Intensa",
    occasions: ["Formal / Gala", "Encontro / Romance", "Noite / Balada"],
    topNotes: "Maçã, Lavanda, Bergamota, Mandarina",
    heartNotes: "Gerânio, Violeta, Jasmim",
    baseNotes: "Baunilha, Cardamomo, Sândalo, Pimenta, Patchouli",
    description: "Perfume de realeza contemporânea. Maçã caramelizada, lavanda e cardamomo descansando sobre sândalo e baunilha.",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 11,
    name: "Terre d'Hermès",
    brand: "Hermès",
    gender: "Masculino",
    salesRank: 11,
    rating: 4.6,
    family: "Amadeirado",
    intensity: "Moderada",
    occasions: ["Dia a Dia / Trabalho", "Formal / Gala"],
    topNotes: "Laranja, Toranja",
    heartNotes: "Pimenta, Sílex, Pelargonium",
    baseNotes: "Vetiver, Cedro, Patchouli, Benjoim",
    description: "A essência da terra e do céu mineral. Laranja amarga, pimenta e um vetiver seco que transmite autoridade e classe.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 12,
    name: "Gentleman Reserve Privée",
    brand: "Givenchy",
    gender: "Masculino",
    salesRank: 12,
    rating: 4.8,
    family: "Oriental/Âmbar",
    intensity: "Intensa",
    occasions: ["Formal / Gala", "Encontro / Romance", "Clima Frio"],
    topNotes: "Bergamota",
    heartNotes: "Íris, Absoluto de Whisky Escocês, Castanha",
    baseNotes: "Madeiras Ambaradas, Benjoim, Cedro",
    description: "Inspirado na destilação de uísque fino. Uma íris atalcada e sedutora combinada com notas ambaradas de carvalho.",
    image: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 13,
    name: "The One for Men EDP",
    brand: "Dolce & Gabbana",
    gender: "Masculino",
    salesRank: 13,
    rating: 4.7,
    family: "Oriental/Âmbar",
    intensity: "Moderada",
    occasions: ["Encontro / Romance", "Noite / Balada"],
    topNotes: "Toranja, Coentro, Manjericão",
    heartNotes: "Cardamomo, Gengibre, Flor de Laranjeira",
    baseNotes: "Âmbar, Tabaco, Cedro",
    description: "O campeão dos encontros a dois. Intimista, quente, charmoso com tabaco adocicado e âmbar aconchegante.",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 14,
    name: "Eros Parfum",
    brand: "Versace",
    gender: "Masculino",
    salesRank: 14,
    rating: 4.5,
    family: "Cítrico/Fresco",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Verão / Calor"],
    topNotes: "Hortelã, Limão Italiano, Maçã Verde",
    heartNotes: "Fava Tonka, Ambroxan, Gerânio",
    baseNotes: "Baunilha de Madagascar, Cedro da Virgínia, Vetiver",
    description: "Mitologia grega em forma de fragrância festiva. Hortelã congelante contrastando com maçã e baunilha expansiva.",
    image: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 15,
    name: "212 VIP Black",
    brand: "Carolina Herrera",
    gender: "Masculino",
    salesRank: 15,
    rating: 4.5,
    family: "Aromático",
    intensity: "Intensa",
    occasions: ["Noite / Balada", "Clima Frio"],
    topNotes: "Absinto, Erva-doce, Anis",
    heartNotes: "Lavanda",
    baseNotes: "Casca de Baunilha Negra, Almíscar",
    description: "Inspirado nas noites exclusivas de Nova York. Um shot inebriante de absinto com baunilha negra marcante.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 16,
    name: "The Most Wanted Parfum",
    brand: "Azzaro",
    gender: "Masculino",
    salesRank: 16,
    rating: 4.7,
    family: "Gourmand",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Clima Frio", "Encontro / Romance"],
    topNotes: "Gengibre Vermelho",
    heartNotes: "Notas Amadeiradas Incandescentes",
    baseNotes: "Baunilha Bourbon",
    description: "Fragrância potente, ultra-doce e picante para quem busca ser o centro absoluto das atenções na noite.",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 17,
    name: "Man In Black",
    brand: "Bvlgari",
    gender: "Masculino",
    salesRank: 17,
    rating: 4.6,
    family: "Oriental/Âmbar",
    intensity: "Intensa",
    occasions: ["Formal / Gala", "Clima Frio", "Encontro / Romance"],
    topNotes: "Rum, Especiarias, Tabaco",
    heartNotes: "Couro, Íris, Tuberosa",
    baseNotes: "Fava Tonka, Madeira Guaiac, Benjoim",
    description: "Uma homenagem ao deus do fogo Vulcano. Notas alcoólicas de rum envelhecido, couro rústico e especiarias nobres.",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 18,
    name: "Le Beau Le Parfum",
    brand: "Jean Paul Gaultier",
    gender: "Masculino",
    salesRank: 18,
    rating: 4.6,
    family: "Gourmand",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Verão / Calor"],
    topNotes: "Abacaxi, Íris, Cipreste, Gengibre",
    heartNotes: "Coco, Notas Amadeiradas",
    baseNotes: "Fava Tonka, Sândalo, Âmbar",
    description: "O jardim proibido de Gaultier em versão potente. Coco cremoso tropical, abacaxi e fava tonka intensa.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 19,
    name: "Explorer",
    brand: "Montblanc",
    gender: "Masculino",
    salesRank: 19,
    rating: 4.5,
    family: "Amadeirado",
    intensity: "Moderada",
    occasions: ["Dia a Dia / Trabalho", "Verão / Calor"],
    topNotes: "Bergamota, Pimenta Rosa, Sálvia Esclareia",
    heartNotes: "Vetiver do Haiti, Couro",
    baseNotes: "Ambroxan, Akigalawood, Patchouli da Indonésia",
    description: "Versatilidade e requinte por um valor inteligente. Estrutura aromática amadeirada com abertura cítrica fresca.",
    image: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 20,
    name: "Prada L'Homme",
    brand: "Prada",
    gender: "Masculino",
    salesRank: 20,
    rating: 4.7,
    family: "Floral",
    intensity: "Moderada",
    occasions: ["Dia a Dia / Trabalho", "Formal / Gala"],
    topNotes: "Néroli, Pimenta Preta, Cardamomo",
    heartNotes: "Íris, Violeta, Gerânio, Âmbar",
    baseNotes: "Cedro, Patchouli",
    description: "O aroma definitivo de camisa social impecavelmente limpa. Íris atalcada, néroli e sofisticação discreta de luxo.",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 21,
    name: "1 Million Parfum",
    brand: "Paco Rabanne",
    gender: "Masculino",
    salesRank: 21,
    rating: 4.4,
    family: "Oriental/Âmbar",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Verão / Calor"],
    topNotes: "Tuberosa Solar, Sal Marinho",
    heartNotes: "Óleo de Monoi, Couro",
    baseNotes: "Âmbar Cinzento, Pinheiro, Ládano",
    description: "A barra de ouro reinventada. Flores brancas solares, sensação salgada de praia e um couro aveludado e potente.",
    image: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 22,
    name: "Born in Roma Intense",
    brand: "Valentino",
    gender: "Masculino",
    salesRank: 22,
    rating: 4.7,
    family: "Oriental/Âmbar",
    intensity: "Intensa",
    occasions: ["Noite / Balada", "Encontro / Romance"],
    topNotes: "Baunilha Bourbon",
    heartNotes: "Lavanda Aromática",
    baseNotes: "Vetiver Fumado",
    description: "A vibração noturna de Roma. O contraste envolvente entre baunilha opulenta e a lavanda fresca com base amadeirada.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 23,
    name: "Dior Homme Intense",
    brand: "Dior",
    gender: "Masculino",
    salesRank: 23,
    rating: 4.9,
    family: "Floral",
    intensity: "Intensa",
    occasions: ["Formal / Gala", "Encontro / Romance", "Clima Frio"],
    topNotes: "Lavanda",
    heartNotes: "Íris da Toscana, Ambreta, Pêra",
    baseNotes: "Cedro da Virgínia, Vetiver",
    description: "Uma obra de arte atemporal. Íris refinadíssima com aspecto aveludado, licoroso e de alta costura francesa.",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 24,
    name: "Invictus Victory Elixir",
    brand: "Paco Rabanne",
    gender: "Masculino",
    salesRank: 24,
    rating: 4.6,
    family: "Gourmand",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Clima Frio"],
    topNotes: "Lavandim, Cardamomo Verde, Pimenta Preta",
    heartNotes: "Incenso, Patchouli",
    baseNotes: "Fava Tonka, Baunilha de Madagascar",
    description: "Doce, ambarado e poderoso. Uma fava tonka licorosa com toques de incenso para quem quer longevidade infinita na pele.",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 25,
    name: "MYSLF Eau de Parfum",
    brand: "Yves Saint Laurent",
    gender: "Masculino",
    salesRank: 25,
    rating: 4.5,
    family: "Floral",
    intensity: "Moderada",
    occasions: ["Dia a Dia / Trabalho", "Encontro / Romance", "Verão / Calor"],
    topNotes: "Bergamota da Calábria",
    heartNotes: "Flor de Laranjeira da Tunísia",
    baseNotes: "Ambrofix, Patchouli da Indonésia",
    description: "Uma declaração de masculinidade fluida. Flores brancas limpas e luminosas sustentadas por ambroxan aveludado.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&auto=format&fit=crop&q=80"
  },

  // ================= FEMININOS & COMPARTILHÁVEIS =================
  {
    id: 26,
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    gender: "Unissex",
    salesRank: 26,
    rating: 4.9,
    family: "Oriental/Âmbar",
    intensity: "Bomba",
    occasions: ["Formal / Gala", "Noite / Balada", "Encontro / Romance"],
    topNotes: "Açafrão, Jasmim Grandiflorum",
    heartNotes: "Madeira de Âmbar, Âmbar Cinzento",
    baseNotes: "Resina de Abeto, Cedro",
    description: "O perfume de nicho mais desejado do planeta. Um algodão doce aéreo e refinado com açafrão, âmbar e rastro lendário.",
    image: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 27,
    name: "Good Girl Eau de Parfum",
    brand: "Carolina Herrera",
    gender: "Feminino",
    salesRank: 27,
    rating: 4.7,
    family: "Gourmand",
    intensity: "Intensa",
    occasions: ["Noite / Balada", "Encontro / Romance", "Clima Frio"],
    topNotes: "Amêndoa, Café, Bergamota, Limão",
    heartNotes: "Tuberosa, Jasmim Sambac, Flor de Laranjeira",
    baseNotes: "Fava Tonka, Cacau, Baunilha, Pralinê, Sândalo",
    description: "O salto agulha icônico da perfumaria feminina. A dualidade irresistível de flores brancas iluminadas e cacau com fava tonka.",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 28,
    name: "Libre Le Parfum",
    brand: "Yves Saint Laurent",
    gender: "Feminino",
    salesRank: 28,
    rating: 4.8,
    family: "Oriental/Âmbar",
    intensity: "Bomba",
    occasions: ["Noite / Balada", "Formal / Gala", "Clima Frio"],
    topNotes: "Gengibre, Açafrão, Mandarina, Bergamota",
    heartNotes: "Flor de Laranjeira, Lavanda Diva Francesa",
    baseNotes: "Baunilha Bourbon, Mel, Fava Tonka, Vetiver",
    description: "A essência ardente da liberdade. Lavanda francesa combinada com flor de laranjeira banhada em açafrão e mel dourado.",
    image: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 29,
    name: "La Vie Est Belle",
    brand: "Lancôme",
    gender: "Feminino",
    salesRank: 29,
    rating: 4.6,
    family: "Gourmand",
    intensity: "Bomba",
    occasions: ["Dia a Dia / Trabalho", "Clima Frio", "Formal / Gala"],
    topNotes: "Groselha Preta, Pêra",
    heartNotes: "Íris Pallida, Jasmim, Flor de Laranjeira",
    baseNotes: "Pralinê, Baunilha, Patchouli, Fava Tonka",
    description: "O manifesto global da felicidade. Íris nobre envolta em uma calda viciante de pralinê, baunilha e groselha.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 30,
    name: "Delina Eau de Parfum",
    brand: "Parfums de Marly",
    gender: "Feminino",
    salesRank: 30,
    rating: 4.9,
    family: "Floral",
    intensity: "Intensa",
    occasions: ["Encontro / Romance", "Formal / Gala", "Verão / Calor"],
    topNotes: "Lichia, Ruibarbo, Bergamota, Noz-moscada",
    heartNotes: "Rosa Turca, Peônia, Almíscar, Petalia, Baunilha",
    baseNotes: "Cashmeran, Cedro, Incenso, Vetiver do Haiti",
    description: "Um buquê floral aristocrático esculpido com lichia e rosa turca sobre um leito sedoso de cashmeran e incenso.",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: 31,
    name: "Black Opium EDP",
    brand: "Yves Saint Laurent",
    gender: "Feminino",
    salesRank: 31,
    rating: 4.7,
    family: "Gourmand",
    intensity: "Intensa",
    occasions: ["Noite / Balada", "Encontro / Romance", "Clima Frio"],
    topNotes: "Pêra, Pimenta Rosa, Flor de Laranjeira",
    heartNotes: "Café Preto, Jasmim, Amêndoa Amarga, Alcaçuz",
    baseNotes: "Baunilha, Patchouli, Cedro, Madeira de Caxemira",
    description: "Dose de adrenalina pura. Café expre